---
layout: post
title: "CQ Queries Demystified"
date: 2014-10-09 18:36
comments: true
categories: [CQ5-AEM, JCR, Queries]
---


The JCR (Java Content Repository) is a data-store at its heart.  Most examples around it demonstrate either building components or walking the Node tree.  It is hard to find examples around queries and the JCR.  To make things worse, we have a number of options and little resourcs to compare them.  My humble goal is to make JCR queries less scary - to myself and others.


== Why Use Queries?

I see 2 primary benefits to using queries compared to "walking the nodes": efficiency and flexibility.

Queries can be *more efficient* when the desired nodes/pages are "sparse".  By sparse, I mean you have to visit a lot more nodes than you keep.  In my recent experience, I was looking for approximately 200-300 pages out of 2,000.  Converting from page traversal to a query improved performance by an order of magnitude (from approximately 10 sec. to well under a second.)

Queries also permit *flexibility in structure*.  http://wiki.apache.org/jackrabbit/DavidsModel#Rule_.231[David's Rules] encourage prioritizing content over formal structure.  If walking the tree of nodes or pages, a developer may limit depth of searching (either a flat level or limited recursion) for simplicity of code and/or performance.  However, in a CMS environment, there are tremendous benefits for authors when they can create an arbitrary taxonomy around their data or pages.


There are two primary APIs for Querying in CQ5:

*  `javax.jcr.query` provides a query interface API in a variety of syntaxes.  http://www.day.com/specs/javax.jcr/javadocs/jcr-2.0/javax/jcr/query/QueryResult.html[QueryResult] can return http://www.day.com/specs/javax.jcr/javadocs/jcr-2.0/javax/jcr/NodeIterator.html[NodeIterators] or http://www.day.com/specs/javax.jcr/javadocs/jcr-2.0/javax/jcr/query/RowIterator.html[RowIterators] (where a http://www.day.com/specs/javax.jcr/javadocs/jcr-2.0/javax/jcr/query/Row.html[Row] can have 1 or more columns. Columns can be +http://www.day.com/specs/javax.jcr/javadocs/jcr-2.0/javax/jcr/Node.html[Node]+ node,  +http://www.day.com/specs/javax.jcr/javadocs/jcr-2.0/javax/jcr/Value.html[Value]+ property, +String+ path or +double+ score).
*  `com.day.cq.search` provides both a REST interface and an API.  The http://docs.adobe.com/docs/en/aem/6-0/develop/ref/javadoc/com/day/cq/search/result/SearchResult.html[SearchResult] can return +Iterator<Resource>+, +Iterator<Node>+, or +List<http://docs.adobe.com/docs/en/aem/6-0/develop/ref/javadoc/com/day/cq/search/result/ResultPage.html[ResultPage]>+ that match the Predicates.

=== Preconditions

CQ5 searches are "powered by" http://lucene.apache.org/[Apache Lucene] (although AEM6 is converting to http://lucene.apache.org/solr/[Apache Solr]).  An important limitation is that indexing only examines Node properties that are 16KB or less in size - so anything larger won't be found by any searching mechanism.

Internally, the queries are converted to an AQM (Abstract Query Model).  The interesting aspect about AQM is the ability to create new query syntaxes and predicates - but that is well beyond the scope of this post.

=== NodeTypes

I recommend paying attention to the http://jackrabbit.apache.org/node-type-visualization.html[NodeType] you use.  At the top of the hierarchy tree is `nt:base`, (so all nodes inherit from it).  Because of this inheritance, most examples show using it as a "works anywhere" approach.  However, I feel this is a poor approach and you would be better served selecting a more appropriate type (`jcr:primaryType` property of your desired nodes).  I would like to highlight:

*  `cq:Page` to match just http://dev.day.com/docs/en/cq/current/javadoc/com/day/cq/wcm/api/Page.html[Page] nodes
*  `cq:PageContent` to easily convert to http://dev.day.com/docs/en/cq/current/javadoc/com/day/cq/commons/inherit/InheritanceValueMap.html[InheritanceValueMap] or http://dev.day.com/docs/en/cq/current/javadoc/org/apache/sling/api/resource/ValueMap.html[ValueMap]
*  `nt:unstructured` to find content nodes for generic components or content

== JCR Queries: http://www.day.com/specs/javax.jcr/javadocs/jcr-2.0/javax/jcr/query/Query.html[+javax.jcr.query+]

[cols="1,2,2", options="header"]
.jcr.query Syntaxes
|===
|Syntax
|Cons
|Pros

|http://jackrabbit.apache.org/api/2.2/org/apache/jackrabbit/commons/query/sql2/package-summary.html[SQL2]
|poor documentation +
no sub-queries +
limited joins +
new functions
|"looks" like a query +
limited joins (K.I.S.S. principle)

|http://jackrabbit.apache.org/api/2.2/org/apache/jackrabbit/spi/commons/query/xpath/package-summary.html[XPath]
|"strange" syntax (http://zvon.org/comp/r/tut-XPath_1.html#intro[Tutorials exist]) +
deprecated in JCR2.0 (yet still supported) +
many XPath functions missing
|maturity & performance +
generic (outside JCR) solution for structure/nodes/attributes

|http://www.day.com/maven/javax.jcr/javadocs/jcr-2.0/javax/jcr/query/qom/QueryObjectModelFactory.html?is-external=true[JQOM]
|poor documentation
|build own query language/API

|SQL
|no longer supported
|N/A
|===


.Query Example
[source,jsp]
----
include::source/_posts/jcr.query.jsp[]
----

TIP: Prefer +Resource+ over +Node+.  It has a cleaner, easier to use API.

TIP: Leverage JSP Expression Language & http://www.tutorialspoint.com/jsp/jsp_standard_tag_library.htm[JSTL] to keep the JSP Template simple & clear.

== QueryBuilder API: http://docs.adobe.com/docs/en/cq/current/javadoc/com/day/cq/search/package-summary.html[+com.day.cq.search+]

[cols="1,2,2", options="header"]
.QueryBuilder Syntaxes
|===
|Syntax
|Cons
|Pros

| http://docs.adobe.com/docs/en/aem/6-0/develop/ref/javadoc/com/day/cq/search/QueryBuilder.html[Java API]
| More code to setup +
node property values must be extracted (just like JCR Queries)
| Iterators for Resources, Nodes (your choice) +
Lists of Pages (natural for search results pages) +
Predicates make "sense" as search conditions

| "RESTful" interface at http://docs.adobe.com/docs/en/aem/6-0/develop/search/querybuilder-api.html[/bin/querybuilder.json]
| grouping predicates is more complex (naming predicates)
| dynamic at runtime +
documented examples of multi properties/values/nesting +
easy to test/explore via browser, +curl+
|===


.Query Example
[source,jsp]
----
include::source/_posts/cq.search.jsp[]
----

TIP: JSPs are best kept as templates with little to no Java in them.  In practice,
move the Java to an OSGi-managed class (Model).  If built outside of CQ5, this permits
rapid unit testing and potentially other JVM languages such as groovy.

REST Example: http://localhost:4502/bin/querybuilder.json?type=cq:Component&path=/apps&orderby=@title&orderby.sort=asc

== Other Resources

* https://wiki.magnolia-cms.com/display/WIKI/JCR+Query+Cheat+Sheet[JCR+Query+Cheat+Sheet] for comparing syntaxes
* http://labs.sixdimensions.com/blog/2014-10-07/9-jcr-sql-2-queries-every-aem-dev-should-know/[9 JCR-SQL2 Queries Every AEM Developer Should Know] by Dan Klco
* http://helpx.adobe.com/experience-manager/kb/HowToDebugJCRQueries.html[HowToDebugJCRQueries.html]
discusses adding loggers to a new file (separate from standard error.log) at the DEBUG level.
This logs the queries executed and their execution time.

=== SQL2 functions (from http://www.day.com/specs/jcr/2.0/6_Query.html#6.6.2%20JCR-SQL2%20Notation[JCR v2.0 Spec])

* CONTAINS(_propName_, _value_)
* ISCHILDNODE() _immediate relationship_
* ISDESCENDANTNODE() _nested relationship_
* ISSAMENODE() _for join conditions_
* LENGTH(_propName_)
* NAME()
* LOCALNAME()
* LOWER() _lower case the text_
* UPPER() _upper case the text_
* SCORE()
* CAST(_literal_ AS _type_)
